import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Physical AI & Humanoid Robotics Textbook',
      items: [
        {
          type: 'category',
          label: 'Part 1: Introduction to Physical AI',
          items: [
            {
              type: 'autogenerated',
              dirName: 'physical-ai-book/part1',
            },
          ],
        },
        {
          type: 'category',
          label: 'Part 2: ROS 2 Fundamentals',
          items: [
            {
              type: 'autogenerated',
              dirName: 'physical-ai-book/part2',
            },
          ],
        },
        {
          type: 'category',
          label: 'Part 3: Robot Simulation with Gazebo',
          items: [
            {
              type: 'autogenerated',
              dirName: 'physical-ai-book/part3',
            },
          ],
        },
        {
          type: 'category',
          label: 'Part 4: NVIDIA Isaac Platform',
          items: [
            {
              type: 'autogenerated',
              dirName: 'physical-ai-book/part4',
            },
          ],
        },
        {
          type: 'category',
          label: 'Part 5: Humanoid Robot Development',
          items: [
            {
              type: 'autogenerated',
              dirName: 'physical-ai-book/part5',
            },
          ],
        },
        {
          type: 'category',
          label: 'Part 6: Conversational Robotics',
          items: [
            {
              type: 'autogenerated',
              dirName: 'physical-ai-book/part6',
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;